esphome:
  name: esp-config

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "dohled"

ota:
  password: "dohled"

wifi:
  ssid: "xxxx"
  password: "xxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-config Fallback Hotspot"
    password: "xxxx"

uart:
  id: mod_bus
  tx_pin: D7
  rx_pin: D6
  baud_rate: 9600
  stop_bits: 1

modbus:
  flow_control_pin: D5
  id: modbus1

modbus_controller:
  - id: epever
    ## the Modbus device addr
    address: 0x1
    modbus_id: modbus1
    setup_priority: -10
sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    name: "Sofar Power"
    id: battery_capacity
    register_type: holding
    address: 0x0C
    # you need to find out a register address, this one works for this particular model. Use modbustool and usb-rs485 convertor to find the required registry hex number
    unit_of_measurement: "W"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - lambda: return (x*10); #watts


web_server:
  port: 80

captive_portal:
    